### ISSUE TITLE
vsgbuilder crashes on Mac

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgExamples#103]
vsgbuilder doesn't run on Mac M1 OS 11.5.1. It crashes due to an uncaught exception. See the IDE output in the appended image.
<img width="1286" alt="vsgbuilder crash on Mac M1" src="https://user-images.githubusercontent.com/31243285/129701050-430f0bfc-b930-4383-8826-5dac166bc995.png">

**Comment by robertosfield** [comment]
The Descriptor::Implementation constructor is reporting a failure of vkAllocateDescriptorSets() by throwing this exception.  It's possible to catch this exception in application if you so wish, in this case the example simply isn't capturing it.  However, in this instance the stack trace is really useful in pinpointing what might be the problem.

In the debugging could you check the values of descriptorSetAllocationInfo and the result returned from the vkAllocateDescriptorSets?

What command line options are you using when running vsgbuilder?

Do other VSG examples like vsgdraw or vsgviewer crash in a similar way?

Have you tried running vsgbuilder on other platforms?  This could be MoltenVK/driver issue.

**Comment by rainergericke** [comment]
Up to commit #4ecb93b00b8af26aeb7dd1744b2628c86d799ae6 vsgbuilder worked on windows and on Mac, as long the number of objects was at least 1 (vsgbuilder -n 1). Actually it still works on Windows. So I have some hope to get the Mac problems healed. vsgdraw and vsgviewer run well on the Mac. I will look at the further details tomorrow.

**Comment by robertosfield** [comment]
On Tue, 17 Aug 2021 at 16:56, Rainer Gericke ***@***.***>
wrote:

> Up to commit #4ecb93b00b8af26aeb7dd1744b2628c86d799ae6 vsgbuilder worked
> on windows and on Mac, as long the number of objects was at least 1
> (vsgbuilder -n 1). Actually it still works on Windows. So I have some hope
> to get the Mac problems healed. vsgdraw and vsgviewer run well on the Mac.
> I will look at the further details tomorrow.
>
Could you run with the Vulkan debug layer enabled via -d to see if that
gives us any more information.

**Comment by rainergericke** [comment]
This is the desired output (vsgbuilder -d)

stateInfo.wireframe = 0
vid->instanceCount = 1
2021-08-18 08:51:36.429283+0200 vsgbuilder[3077:49276] Metal API Validation Enabled
2021-08-18 08:51:36.449843+0200 vsgbuilder[3077:49276] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960 - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x112689af0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x112689af0[] supports it The Vulkan spec states: If the [VK_KHR_portability_subset] extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset". (https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
    Objects: 1
        [0] 0x112689af0, type: 2, name: NULL
VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307(ERROR / SPEC): msgNum: 562402104 - Validation Error: [ VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307 ] Object 0: handle = 0xec4bec000000000b, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID = 0x21859338 | vkAllocateDescriptorSets(): Unable to allocate 1 descriptors of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER from VkDescriptorPool 0xec4bec000000000b[]. This pool only has 0 descriptors of this type remaining. The Vulkan spec states: descriptorPool must have enough free descriptor capacity remaining to allocate the descriptor sets of the specified layouts (https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307)
    Objects: 1
        [0] 0xec4bec000000000b, type: 22, name: NULL
libc++abi: terminating with uncaught exception of type vsg::Exception
terminating with uncaught exception of type vsg::Exception
(lldb)

**Comment by robertosfield** [comment]
On Wed, 18 Aug 2021 at 07:55, Rainer Gericke ***@***.***>
wrote:

> This is the desired output (vsgbuilder -d)
>
> stateInfo.wireframe = 0
> vid->instanceCount = 1
> 2021-08-18 08:51:36.429283+0200 vsgbuilder[3077:49276] Metal API
> Validation Enabled
> 2021-08-18 08:51:36.449843+0200 vsgbuilder[3077:49276] +[MTLIOAccelDevice
> registerDevices]: Zero Metal services found
> VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960
> - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0:
> handle = 0x112689af0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID =
> 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled
> because physical device VkPhysicalDevice 0x112689af0[] supports it The
> Vulkan spec states: If the [VK_KHR_portability_subset] extension is
> included in pProperties of vkEnumerateDeviceExtensionProperties,
> ppEnabledExtensions must include "VK_KHR_portability_subset". (
> https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451
> )
>

Does this mean we should be using the compatibility profile for macOS?
What happens when you run "vsgdraw -d"?

Objects: 1
> [0] 0x112689af0, type: 2, name: NULL
> VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307(ERROR / SPEC):
> msgNum: 562402104 - Validation Error: [
> VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307 ] Object 0: handle =
> 0xec4bec000000000b, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID =
> 0x21859338 | vkAllocateDescriptorSets(): Unable to allocate 1 descriptors
> of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER from VkDescriptorPool
> 0xec4bec000000000b[]. This pool only has 0 descriptors of this type
> remaining. The Vulkan spec states: descriptorPool must have enough free
> descriptor capacity remaining to allocate the descriptor sets of the
> specified layouts (
> https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorPool-00307
> )
> Objects: 1
> [0] 0xec4bec000000000b, type: 22, name: NULL
> libc++abi: terminating with uncaught exception of type vsg::Exception
> terminating with uncaught exception of type vsg::Exception
>
That suggests that the collection of vkDescriptorSet/Descriptor resources
required by the scene graph isn't picking up on all the required elements.

I'll be able to dig into this more tomorrow.

**Comment by rainergericke** [comment]
vsgdraw -d

gives

2021-08-18 10:35:46.351265+0200 vsgdraw[4347:88767] Metal API Validation Enabled
2021-08-18 10:35:46.361976+0200 vsgdraw[4347:88767] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960 - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x125869750, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x125869750[] supports it The Vulkan spec states: If the [VK_KHR_portability_subset] extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset". (https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
    Objects: 1
        [0] 0x125869750, type: 2, name: NULL
2021-08-18 10:35:49.072127+0200 vsgdraw[4347:88767] GetDYLDEntryPointWithImage(/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit,_NSCreateAppKitServicesMenu) failed.
Program ended with exit code: 0

**Comment by robertosfield** [comment]
On Wed, 18 Aug 2021 at 09:37, Rainer Gericke ***@***.***>
wrote:

> vsgdraw -d
>
> gives
>
> 2021-08-18 10:35:46.351265+0200 vsgdraw[4347:88767] Metal API Validation
> Enabled
> 2021-08-18 10:35:46.361976+0200 vsgdraw[4347:88767] +[MTLIOAccelDevice
> registerDevices]: Zero Metal services found
> VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960
> - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0:
> handle = 0x125869750, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID =
> 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled
> because physical device VkPhysicalDevice 0x125869750[] supports it The
> Vulkan spec states: If the [VK_KHR_portability_subset] extension is
> included in pProperties of vkEnumerateDeviceExtensionProperties,
> ppEnabledExtensions must include "VK_KHR_portability_subset". (
> https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451
> )
> Objects: 1
> [0] 0x125869750, type: 2, name: NULL
> 2021-08-18 10:35:49.072127+0200 vsgdraw[4347:88767]
> GetDYLDEntryPointWithImage(/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit,_NSCreateAppKitServicesMenu)
> failed.
> Program ended with exit code: 0
>
Thanks for the test.  Looks like we'll need to add some test and add in the
Instance/Device setup.

**Comment by robertosfield** [comment]
A quick update.  I've recreated the debug error under Linux so will be able
to hunt it down and solve it.

**Comment by robertosfield** [comment]
I've fixed several bugs in vsg::Builder that were being picked up by the Vulkan debug layer.  The fixes are now merged with VulkanSceneGraph master.  

   [https://github.com/vsg-dev/VulkanSceneGraph/pull/299](https://github.com/vsg-dev/VulkanSceneGraph/pull/299)

I have also update vsgExamples master with a few fixes/ and improvements, so worth pulling as well.

@rainergericke Could you test out these changes, hopefully they will fix things under MacOS as well.  Also could you let me know the VulkanSDK/MoltenVK version and source you are using?

**Comment by rainergericke** [comment]
Good news: vsgbuilder works correctly now. vsgbuilder -d outputs still a message yet:

VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960 - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x1326c83e0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x1326c83e0[] supports it The Vulkan spec states: If the [VK_KHR_portability_subset] extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset". (https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
    Objects: 1
        [0] 0x1326c83e0, type: 2, name: NULL
Average frame rate = 119.182

vsgbuilder -n 20000 gives this
<img width="1277" alt="Bildschirmfoto 2021-08-20 um 15 05 34" src="https://user-images.githubusercontent.com/31243285/130237705-ecf68876-2482-4880-b415-b3430f2dc7f0.png">

MoltenVK seems to be version 1.1.4 (from vulkaninfo output).

**Comment by robertosfield** [comment]
On Fri, 20 Aug 2021 at 14:16, Rainer Gericke ***@***.***>
wrote:

> Good news: vsgbuilder works correctly now. vsgbuilder -d outputs still a
> message yet:
>
Excellent.  Pretty decent performance too.  What hardware do you have?

For reference I'm getting 280fps on my Linux/NVidia 2060 system for:

    vsgbuilder -n 20000 --IMMEDIATE

--IMMEDIATE selects a swap buffer without vsync.


> VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960
> - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0:
> handle = 0x1326c83e0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID =
> 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled
> because physical device VkPhysicalDevice 0x1326c83e0[] supports it The
> Vulkan spec states: If the [VK_KHR_portability_subset] extension is
> included in pProperties of vkEnumerateDeviceExtensionProperties,
> ppEnabledExtensions must include "VK_KHR_portability_subset". (
> https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451
> )
> Objects: 1
> [0] 0x1326c83e0, type: 2, name: NULL
>
I'll look into that this afternoon.

**Comment by rainergericke** [comment]
I have a M1 (arm64) Mac with integrated GPU, 8 kernels each. For a system-on-a-chip the performance is ok. 

vsgbuilder -n 20000 --IMMEDIATE

runs on my machine with 82.1099 fps.

**Comment by robertosfield** [comment]
@rainergericke I've started working on the VK_KHR_portability_subset debug error, first step has to been to add a PhysicalDevive::enumerateDeviceExtensionProperties() wrapper for the [vkEnumerateInstanceExtensionProperties](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkEnumerateInstanceExtensionProperties.html) call.  

This addition and a call to it and it from Window::initDevice() with output to the console of results could be found in a new [VK_KHR_portability_subset](https://github.com/vsg-dev/VulkanSceneGraph/tree/VK_KHR_portability_subset) branch of VulkanSceneGraph.  Could you check out this branch and run vsgdraw and post the results?

Once we've confirm what the extension name is and it's mapping across I think from debug layer report suggests we need to add this to the request layers.  I will need to look online to see an example of doing what is required for macOS now, please post a link if you've come across a good guide.

**Comment by rainergericke** [comment]
rainerge@Rainers-iMac-M1 Debug % ./vsgdraw -d                             
Window::_initDevice() extensionProperties.size() = 59
    extensionProperty.extensionName = VK_KHR_16bit_storage, specVersion = 1
    extensionProperty.extensionName = VK_KHR_8bit_storage, specVersion = 1
    extensionProperty.extensionName = VK_KHR_bind_memory2, specVersion = 1
    extensionProperty.extensionName = VK_KHR_create_renderpass2, specVersion = 1
    extensionProperty.extensionName = VK_KHR_dedicated_allocation, specVersion = 3
    extensionProperty.extensionName = VK_KHR_depth_stencil_resolve, specVersion = 1
    extensionProperty.extensionName = VK_KHR_descriptor_update_template, specVersion = 1
    extensionProperty.extensionName = VK_KHR_device_group, specVersion = 4
    extensionProperty.extensionName = VK_KHR_driver_properties, specVersion = 1
    extensionProperty.extensionName = VK_KHR_external_fence, specVersion = 1
    extensionProperty.extensionName = VK_KHR_external_memory, specVersion = 1
    extensionProperty.extensionName = VK_KHR_external_semaphore, specVersion = 1
    extensionProperty.extensionName = VK_KHR_get_memory_requirements2, specVersion = 1
    extensionProperty.extensionName = VK_KHR_imageless_framebuffer, specVersion = 1
    extensionProperty.extensionName = VK_KHR_image_format_list, specVersion = 1
    extensionProperty.extensionName = VK_KHR_maintenance1, specVersion = 2
    extensionProperty.extensionName = VK_KHR_maintenance2, specVersion = 1
    extensionProperty.extensionName = VK_KHR_maintenance3, specVersion = 1
    extensionProperty.extensionName = VK_KHR_multiview, specVersion = 1
    extensionProperty.extensionName = VK_KHR_portability_subset, specVersion = 1
    extensionProperty.extensionName = VK_KHR_push_descriptor, specVersion = 2
    extensionProperty.extensionName = VK_KHR_relaxed_block_layout, specVersion = 1
    extensionProperty.extensionName = VK_KHR_sampler_mirror_clamp_to_edge, specVersion = 3
    extensionProperty.extensionName = VK_KHR_sampler_ycbcr_conversion, specVersion = 14
    extensionProperty.extensionName = VK_KHR_shader_draw_parameters, specVersion = 1
    extensionProperty.extensionName = VK_KHR_shader_float16_int8, specVersion = 1
    extensionProperty.extensionName = VK_KHR_shader_subgroup_extended_types, specVersion = 1
    extensionProperty.extensionName = VK_KHR_storage_buffer_storage_class, specVersion = 1
    extensionProperty.extensionName = VK_KHR_swapchain, specVersion = 70
    extensionProperty.extensionName = VK_KHR_swapchain_mutable_format, specVersion = 1
    extensionProperty.extensionName = VK_KHR_timeline_semaphore, specVersion = 2
    extensionProperty.extensionName = VK_KHR_uniform_buffer_standard_layout, specVersion = 1
    extensionProperty.extensionName = VK_KHR_variable_pointers, specVersion = 1
    extensionProperty.extensionName = VK_EXT_debug_marker, specVersion = 4
    extensionProperty.extensionName = VK_EXT_descriptor_indexing, specVersion = 2
    extensionProperty.extensionName = VK_EXT_fragment_shader_interlock, specVersion = 1
    extensionProperty.extensionName = VK_EXT_hdr_metadata, specVersion = 2
    extensionProperty.extensionName = VK_EXT_host_query_reset, specVersion = 1
    extensionProperty.extensionName = VK_EXT_image_robustness, specVersion = 1
    extensionProperty.extensionName = VK_EXT_inline_uniform_block, specVersion = 1
    extensionProperty.extensionName = VK_EXT_memory_budget, specVersion = 1
    extensionProperty.extensionName = VK_EXT_post_depth_coverage, specVersion = 1
    extensionProperty.extensionName = VK_EXT_private_data, specVersion = 1
    extensionProperty.extensionName = VK_EXT_robustness2, specVersion = 1
    extensionProperty.extensionName = VK_EXT_scalar_block_layout, specVersion = 1
    extensionProperty.extensionName = VK_EXT_shader_stencil_export, specVersion = 1
    extensionProperty.extensionName = VK_EXT_shader_viewport_index_layer, specVersion = 1
    extensionProperty.extensionName = VK_EXT_subgroup_size_control, specVersion = 2
    extensionProperty.extensionName = VK_EXT_texel_buffer_alignment, specVersion = 1
    extensionProperty.extensionName = VK_EXT_texture_compression_astc_hdr, specVersion = 1
    extensionProperty.extensionName = VK_EXT_vertex_attribute_divisor, specVersion = 3
    extensionProperty.extensionName = VK_AMD_gpu_shader_half_float, specVersion = 2
    extensionProperty.extensionName = VK_AMD_negative_viewport_height, specVersion = 1
    extensionProperty.extensionName = VK_AMD_shader_image_load_store_lod, specVersion = 1
    extensionProperty.extensionName = VK_AMD_shader_trinary_minmax, specVersion = 1
    extensionProperty.extensionName = VK_IMG_format_pvrtc, specVersion = 1
    extensionProperty.extensionName = VK_INTEL_shader_integer_functions2, specVersion = 1
    extensionProperty.extensionName = VK_GOOGLE_display_timing, specVersion = 1
    extensionProperty.extensionName = VK_NV_glsl_shader, specVersion = 1
VUID-VkDeviceCreateInfo-pProperties-04451(ERROR / SPEC): msgNum: 976972960 - Validation Error: [ VUID-VkDeviceCreateInfo-pProperties-04451 ] Object 0: handle = 0x1356b72f0, type = VK_OBJECT_TYPE_PHYSICAL_DEVICE; | MessageID = 0x3a3b6ca0 | vkCreateDevice: VK_KHR_portability_subset must be enabled because physical device VkPhysicalDevice 0x1356b72f0[] supports it The Vulkan spec states: If the [VK_KHR_portability_subset] extension is included in pProperties of vkEnumerateDeviceExtensionProperties, ppEnabledExtensions must include "VK_KHR_portability_subset". (https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451)
    Objects: 1
        [0] 0x1356b72f0, type: 2, name: NULL

**Comment by robertosfield** [comment]
Thanks, the portability extension is there so it looks like the new method
is working fine, will now need to add a check for the extension and then
enable it when setting up the vsg::Device.  Will do that tomorrow and ping
you to test it,

>

**Comment by robertosfield** [comment]
@rainergericke I have checked in a change to Device constructor to do the test for VK_KHR_portability_subset.  Could you pull from the VulkanSceneGraph [VK_KHR_portability_subset](https://github.com/vsg-dev/VulkanSceneGraph/commit/4edb7bddd3eddf5cd2f05705d37901ca1014e6f9) branch and then run vsgdraw -d to see if the warning is resolved:

**Comment by rainergericke** [comment]
vsgdraw -d doesn't generate a message at all now, it just works, great!

**Comment by robertosfield** [comment]
On Sun, 22 Aug 2021 at 09:57, Rainer Gericke ***@***.***>
wrote:

> vsgdraw -d doesn't generate a message at all now, it just works, great!
>
That's excellent news. With this confirmation I've merged the
VK_KHR_portability_subset into VSG master.

Thanks for the testing.
