### ISSUE TITLE
vsgskybox refuses to load models/skybox.vsgb

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgExamples#140]
Strange error when calling this:
_vsgskybox models/teapot.vsgt --skybox models/skybox.vsgb_
**Error: failed to load cubemap file : models/skybox.vsgb**

skybox.vsgb exists and can be opened with:
_vsgviewer models/skybox.vsgb_

This error occurs on MacOS 12.2 and on Windows 10 as well.
Vulkan version: 1.3.204.0 on both systems.

**Comment by robertosfield** [comment]
skybox.vsgb is a scene graph file not a cubemap texture like vsgskybox --skybox cubemmap.fmt is expecting.

Tru:

      vsgskybox models/zl.vsgt textures/skybox.dds
