### ISSUE TITLE
Image Displaying in ImGui

### ISSUE THREAD

**Issue by hobbeshunter** [vsg-dev/vsgExamples#205]
Nice work!

Can you provide an example on how to load and display an image with Dear ImGui? I tried to work along [this tutorial](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#Example-for-Vulkan-users) but failed.

In the end ImGui just needs a `VkDescriptorSet` but I'm unsure how to set everything up with the vsg classes.

Thanks in advance!

**Comment by robertosfield** [comment]
The Issue track is really for bugs and build issues.  For general support questions like this could you please post a question to the VSG Discussion forum:

https://github.com/vsg-dev/VulkanSceneGraph/discussions

**Comment by rolandhill** [comment]
Hi Martin,

Tim got it working in vsgCs.
https://github.com/vsg-dev/VulkanSceneGraph/discussions/690

Regards,
Roland

**Comment by hobbeshunter** [comment]
Thanks a lot. I got it working. 

Maybe `ImageComponent` find its way into vsgImGui?

Although it was a bit tricky that it is necessary to first call `viewer->compile()` and then `viewer->compileManager->compile(image)`. Maybe a warning/ error message can help when doing it the other way around.

**Comment by robertosfield** [comment]
W.r.t ImageComponent I'll defer to @timoore to submit a PR to vsgImGui, but if he's too busy I guess others can jump in.  It may be possible to refine it further.  Can't comment on the details till I review the code and test it out.
