### ISSUE TITLE
.spv files should be built from source or removed entirely

### ISSUE THREAD

**Issue by timoore** [vsg-dev/vsgExamples#208]
The .spv binary shader file situation in data/shaders is a bit confused. Newer shaders, such as the standard shaders and computevertex, have no .spv files at all.  The rest are fairly old. They may be useful examples for cases where VSG is built without shader compilation and the user doesn't want to use the built-in shaders. However, because the .spv files are not built from source, there's no guarantee that they are consistant with their source, other than the diligence of the commiter.

A complication is that the standard shaders can't easily be built with the Vulkan SDK tools because of all the variants supported in each shader. That's a different issue that I will address in another post.

So, I propose that either the .spv files are removed, or rules are added to CMake files (for example, https://gist.github.com/evilactually/a0d191701cb48f157b05be7f74d79396) to compile .spv for the shaders for which it makes sense.

**Comment by robertosfield** [comment]
The .spv files mostly date back to a time before the VSG has shade compilation built in, and in some instances could be removed entirely so a review of all the examples and the .spv they use would be appropriate.

For the .spv files left using vsgconv to do this should be fine as long as the core VSG has shader compilation built in.  Invoking these from cmake would make sense, but not something I think is a big priority as it's very dev's that should ever need to do this.  

W.r.t shader variables#defines that are specific to the VSG, this really is for shaders that use pragmatic shader composition and there's no way around needing to do this within the context of a VSG application.  These are shaders that would be compiled to a specific .spv though so not something would need to be included in converter from GLSL to .spv.

The route for the examples that still use .spv would be to compile the .spv into the example as is done for the shaders built-in to the VSG itself.  The _vsgconv myshader.vert myshader.cpp capability could provide this as an easy to maintain solution.

**Comment by robertosfield** [comment]
Just going through old Issues and have checked the examples for which .spv files are still being used and have removed the no longer used .spv's: 97a97b044ba68b59c4309f74f4cb52bb4c060436
