### ISSUE TITLE
how to render models with tileData?

### ISSUE THREAD

**Issue by albert8271** [vsg-dev/vsgExamples#227]
There are some models with tileData in the data/models, like  "openstreetmap.vsgt" and "readymap.vsgt", 
how to render it ? I used vsgviewer ,but show nothing.  
thank you !

**Comment by robertosfield** [comment]
The vsgExamples/data/models/openstreetmap.vsgt requires http support that is provided by vsgXchange::curl, so you'll need to build vsgXchange with curl and then rebuild vsgExamples.
