### ISSUE TITLE
How to create the included spv files

### ISSUE THREAD

**Issue by timprepscius** [vsg-dev/vsgExamples#23]
This will probably be obvious to me at some later date, however:

How are each of the .spv files within data/shaders generated?
How are the font files with data/fonts generated?
How are texture files with data/textures generated?

Is there a script which does this?
If there is not a script which does this, could you create a script which does this, so that the generation method is explicit?

Where are the source-data files for the generated files?

Could you include in your repo, the sources for these files and the script which generates them.

Thanks

**Comment by vsg-dev** [comment]
The data/shaders directory contains the SPIR-V .spv files and the GLSL .vert/.frag shaders they were derived from:

    https://github.com/vsg-dev/vsgExamples/tree/master/data/shaders

To convert the GLSL to SPIR-V you'll need to use glslangValidator which is part of the glslang project:

   https://github.com/KhronosGroup/glslang

The new vsgXchange project also has a code path that uses glslang as a library and is able to convert GLSL shaders in scene graphs to SPIR_V that Vulkan requires.  The vsgXchange also has a vsgconv utility program that allows you to convert GLSL files to SPIR-V on the command line i.e.

    vsgconv myshader.frag myshader.spv

The vsgXchange library and vsgconv utility program will also be able to convert 3d model files to native VSG .vsgt and .vsgb files.  It's still very early in it's existence though so 3d model support is not developed yet.

**Comment by timprepscius** [comment]
Could you write a script that does all of the vsgconv transformations, and include it in your repository.

I think it is fair to assume that vsgconv exists on the path somewhere.
(Because if it doesn't, it will be obvious to the repo-downloader that they need to download vsgconv)

**Comment by vsg-dev** [comment]
I don't understand what you are thinking what a provided script would do, how users want to invoke tools like vsgconv will depend entirely on the specifics of their data so it's really down to them to write them own scripts if appropriate.  

Users will either just invoke vsgconv how they want, or like to vsgXchange and implement their own conversion applications or just embed this work in their own application.

I really don't envisage the various VSG supporting projects to start supplying scripts to users, the VSG is cross platform project, it's a low level tool meant for a wide range of uses and were possible avoiding making choices for users and how they should manage their own workflows.

Scripting is really something I would expect users of the various VSG components to write so streamline things for their particular usage case and art path routes etc.  So if you wrote a game engine or a simulator ontop of the VSG, then these would have scripts written for that particular usage case.  The VSG is a level below a game engine/simulator.
