### ISSUE TITLE
If vsgTransform is no command line parameter, it will crash.

### ISSUE THREAD

**Issue by chenhaoen** [vsg-dev/vsgExamples#231]
[https://github.com/vsg-dev/vsgExamples/blob/master/examples/nodes/vsgtransform/vsgtransform.cpp](url)

Line 43 should be changed to if ( argc < = 1 ).

**Comment by robertosfield** [comment]
Thanks for spotting this error, now fixed : b7066502215d60a51ebfb45f57e829cc750c9e0d
