### ISSUE TITLE
Compiling issues for vsgvolume example

### ISSUE THREAD

**Issue by VasanthBalguri** [vsg-dev/vsgExamples#257]
Hi Team,

Unable to compile vsgvolume with following error
/home/vasanth/custom/include/vsg/core/Inherit.h:37: error: undefined reference to `vsgXchange::all::all()'

I can see that in vsgvolume.cpp there is no macro definition to skip vsgXchange, but i would like to use this feature.
Did I compile vsgXchange wrong, the error message is tricky, I used latest master branch for compiling vsgXchange and 1.0.9-rc1 for compiling vsg.

Thanks and Regards,
Vasanth

**Comment by robertosfield** [comment]
Doing a review of vsgvolume.cpp I see if doesn't have an #ifdef checks vsgXchange being available so I've added these so you should now be able to compile vsgvolume without having vsgXchange installed.  2d9c90e18d964876f8f42a67fd18f7eb47d9cd4a

W.r.t vsgXchange, I can only guess that something has gone wrong with the compile and install of vsgXchange such that vsgExamples isn't finding where vsgXchange is located.

**Comment by VasanthBalguri** [comment]
Apologies, 

Think CMake is unable to find my compiled vsgXchange, although I have installed it correctly. I need to figure it out somehow :(

![image](https://github.com/vsg-dev/vsgExamples/assets/20721849/c4ece551-ab1d-4ea5-ad2e-0b5ab4014ab5)
I have configured it correctly

The compile error is as following

![image](https://github.com/vsg-dev/vsgExamples/assets/20721849/94288be8-4aa2-4652-9100-83b1ed3f4923)

Help is appreciated :)

Regards,
Vasanth

**Comment by VasanthBalguri** [comment]
Okay will close the issue for now, will update here anything I find

**Comment by robertosfield** [comment]
Are you still seeing this error with the commit checked into vsgExamples?

When building with CMake generated Makefiles you can use:

 make VERBOSE=1

This will report all the parameters passed to compile and link example library and program, this might provide a clue to what is going wrong on your system. 

What OS and CMake/Compiler versions are you using?
