### ISSUE TITLE
vertex and fragment source for vert_PushConstants.spv and frag_PushConstants.spv

### ISSUE THREAD

**Issue by VasanthBalguri** [vsg-dev/vsgExamples#266]
Hi Robert,

I was not able to find source for shaders used in examples.
sharing it will help us a lot.

Please correct me if it is already shared somewhere in source.

Thanks and Regards,
Vasanth

**Comment by rolandhill** [comment]
Hi Vasanth,

The shader source code is in the vsgExamples repository under data/shaders.

Cheers,
Roland

**Comment by VasanthBalguri** [comment]
Hi,

I couldnt find vert_PushConstants.vert and frag_PushConstants.frag in the
source code

Regards,
Vasanth

**Comment by rolandhill** [comment]
I think they're the names of the compiled spv code. For source,
try shader_PushConstants.vert and shader_PushConstants.frag in that same
directory.

**Comment by robertosfield** [comment]
As Roland says all the .frag and .vert variants of the shaders are there, but I do need to do a clean out/standardization of naming as I think some of the older .spv/.frag/.vert files don't look consistent from the quick look I've just done.

**Comment by VasanthBalguri** [comment]
I am closing this issue as I got my answer, but it would be really good if the naming is standardized.
