### ISSUE TITLE
VSG_INSTANCE_POSITIONS format change

### ISSUE THREAD

**Issue by LeeRiva** [vsg-dev/vsgExamples#287]
I am wondering about a change in 6e243f3.. in pbr.cpp, the 'vsg_position' attribute got its format changed from VK_FORMAT_R32G32B32_SFLOAT to VK_FORMAT_R8G8B8A8_UINT. I don't see this change in the 'flat' and 'phong' shader sets, and I don't see any changes in the Builder class (which I assume would be needed, since - in my limited understanding - the layout/size of the whole attribute changes?)

In general, would you prefer if people opened an issue about things like that, or would it better if we commented on the PR (I am not sure if you'd get notifications about such things..)?

**Comment by robertosfield** [comment]
Positing an issue and extra info like likes to a PR if you think that's the source of the problem works for me.

**Comment by robertosfield** [comment]
The type change to pbr.cpp was an error, I've fixed it and checked it in:

7714e21022a643291cd38a799a9f670675e47adc
