### ISSUE TITLE
How to display a point on the earth map?

### ISSUE THREAD

**Issue by kahlenberg** [vsg-dev/vsgExamples#294]
Hi,

I built the vsgExample and run the vsgpagedlod example. It shows the earth without problem. I want to show a point in a WSG84 position and I have some questions:

1) How can I display a red dot at a given coordinates?
3) How can I overlay another 3D object at a given coordinates, for example a car or so?
2) Is it possible to show 3D buildings on the map? If yes how?

Thanks.

**Comment by robertosfield** [comment]
Could you use the official forum for support questions?

https://github.com/vsg-dev/VulkanSceneGraph/discussions

This keeps all the support discussion in one place where everyone can read/contribute to and keep the Issue trackers dedicated to reports of build issues or bugs. Thanks,
