### ISSUE TITLE
vsgvolume is actually broken on Windows 11 and Ubuntu 22.4

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgExamples#299]
On the Mac vsgvolume runs normally.
On Ubuntu 22.04 a black window opens with no content. No reaction to keys strokes.
On Windows 11 acts like Ubuntu, a debugger hint pops up.

Vulkan Version on all systems is v1.3.280.x
VSG Version on all systems is v1.1.2

**Comment by robertosfield** [comment]
When you say broken and you getting crashes or is it just no visuals?

**Comment by robertosfield** [comment]
I have tracked the problem down to a stray increment,
