### ISSUE TITLE
DescriptorPool warning when using compileManager with storage buffers

### ISSUE THREAD

**Issue by theodoregoetz** [vsg-dev/vsgExamples#312]
See #311 

We are trying to use the compileManager when changing out portions of the scene and VSG is emitting this warning after a few iterations compiling shaders that use storage buffers. This may or may not be unique to storage buffer usage, but we'd like some help debugging this issue.

```
Warning: Context::reserve(const ResourceRequirements& requirements) 
invalid combination of required_maxSets (0) & required_descriptorPoolSizes (1) 
unable to allocate DescriptorPool.
```

**Comment by rolandhill** [comment]
Hi,

This PR addressed this issue
https://github.com/vsg-dev/VulkanSceneGraph/pull/961. I've been using it
for a year or so and it all works perfectly well. I haven't updated VSG for
around a month or 2 and now see that it doesn't pass all checks. It's only
a single line change though so should give you a good place to start and
the discussion will help.

Regards,
Roland

**Comment by rolandhill** [comment]
It's actually 2 lines changed, not 1. I just re-based the PR on the latest VSG and it all appears to work OK. The check that didn't pass says that the Android test was cancelled. Give it a try and let us know if it works for you - it would be good to have another test.

Roland
