### ISSUE TITLE
how to set update callback for a node

### ISSUE THREAD

**Issue by yexiaoshen** [vsg-dev/vsgExamples#48]
hi,
    if i want to set update callback for a vsgNode like this code  in osg :
---------------------------------------------------------
   RotateTransform *transform = new RotateTransform;
   transform->setName( "XXX"  );
   RotUpdateCallback *cc =
   new RotUpdateCallback( XXX, XXX, XXX );
   transform->setUpdateCallback( cc );
----------------------------------------------------------
what  should I do,or is there an example for this ？
thanks！！

**Comment by robertosfield** [comment]
Could you please post support questions to the vsg-users as the discussion will be able to able to help all interested parties now and in the future. Thanks.
