### ISSUE TITLE
vsgcompute issues with MoltenVK..

### ISSUE THREAD

**Issue by oscarbg** [vsg-dev/vsgExamples#56]
using latest MoltenVK 1.2.135..
Are you aware?
```
 ./vsgcompute
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:26:26: error: 'function_constant' has a duplicate index '2'
constant uint _167_tmp [[function_constant(2)]];
                         ^
program_source:24:26: note: duplicate 'function_constant' index '2' here
constant uint _166_tmp [[function_constant(2)]];
                         ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
libc++abi.dylib: terminating with uncaught exception of type vsg::Exception
zsh: abort      ./vsgcompute
```

**Comment by robertosfield** [comment]
Hi Oscar,

I don't have macOS system to test against so have to rely on the community
for this.  Could you run  vsgcompute with the Vulkan debug layer enabled in
MoltenVK supports it.  Run with :

    vsgcompute -d

Another step would be to run with the Vulkan api layer :

    vsgcompute -d -a

It might be that no errors are produced as I everything runs cleanly under
Linux and reports no errors, and it'll be the same Vulkan API calls being
used.  It could be that it's a MoltenVK error in which passing this error
on to the MoltenVK to them might be required.

The vsgcompute example is inspired by the vullan_minimal_compute project
hosted on github, if the above don't provide any leads then it would be
worth checking if it runs OK with MoltenVK.

>

**Comment by robertosfield** [comment]
I've had a look over the shaders/shader.comp that generates the saders/comp.spv that is used by the vsgcompute example and the part that looks like it might relate to the warning is the use of specialization constants.  It looks like there are others who've hit upon this issue too:

   https://github.com/KhronosGroup/MoltenVK/issues/231

Which just so happens to have a comment from @oscarbg on the Issue :-)

A workaround would be to avoid the use of specialization constants but it's valuable feature so I'm reluctant to apply to workaround for what could be a bug in MoltenVK.
