### ISSUE TITLE
Question: cmake dependency on vsg_glslang

### ISSUE THREAD

**Issue by CBenghi** [vsg-dev/vsgExamples#84]
Hello,

I get an error running cmake on the project 

```
Could not find a package configuration file provided by "vsg_glslang" with   any of the following names:
    vsg_glslangConfig.cmake
    vsg_glslang-config.cmake
```

I've set the path to a freshly compiled master of VSG in CMAKE_PREFIX_PATH, and that's found correctly.
Is there another dependency I'm missing?

Thanks,
Claudio

**Comment by robertosfield** [comment]
On Sat, 13 Feb 2021 at 10:19, Claudio Benghi <notifications@github.com>
wrote:

> I get an error running cmake on the project
>
> Could not find a package configuration file provided by "vsg_glslang" with   any of the following names:
>     vsg_glslangConfig.cmake
>     vsg_glslang-config.cmake
>
> I've set the path to a freshly compiled master of VSG in
> CMAKE_PREFIX_PATH, and that's found correctly.
> Is there another dependency I'm missing?
>
If VSG is built and can find glslang (it's now part of the official
VulkanSDK) the VSG should install vsg_glslangConfig.cmake alongside the
vsgConfig.cmake.

What platform are you working on?

Which version of the Vulkan/VulkanSDK are you using?

**Comment by CBenghi** [comment]
Vulkan1.2.162.1
I've tried using vs 2017 (updated yesterday) on Windows 10, with the current master of vsg.
I'll look for those files and see if I was missing something.
I'll also try again with vs2019.
Thanks!

**Comment by robertosfield** [comment]
This is topic that has been briefly mentioned on the vsg-users group:

    [https://groups.google.com/g/vsg-users/c/h3m7Wgvj7BQ/m/--jjnq17BAAJ](https://groups.google.com/g/vsg-users/c/h3m7Wgvj7BQ/m/--jjnq17BAAJ)

I'm not a Windows user so can't address issue directly.  It looks like explicitly pointing CMake at the place where the vsg_glslang.cmake is installed via the CMake gui is the one possible route.  Debug build vs Release build might also be a factor.

It may be best to join vsg-users start a thread about best practices for Windows builds.  Hopefully the Window devs in the community we'll be able to refine things so things work better out of the box.

**Comment by rhabacker** [comment]
It would be helpful to see the list of installed files of the VSG packages e.g. the output from (n)make install  and the result of running cmake ... --trace-expand in vsgExamples to see where it looks for cmake support files.

**Comment by robertosfield** [comment]
@rhabacker what paths do you see when you build and install VSG, vsgXchange etc and then build the vsgExamples?  Are you manually setting install paths or leaving them on defaults?

**Comment by rhabacker** [comment]
I'm using default pathes on a local development system with openSUSE. 

Further investigation shows that this issue happens when the glslang package wasn't found. In that case cmake tries to search for an installed package named 'vsg_glslang' (see https://github.com/vsg-dev/VulkanSceneGraph/blob/master/CMakeLists.txt#L85) , which is generated by the VulkanSceneGraph package and therefore could not be available on building vulkanSceneGraph.

**Comment by robertosfield** [comment]
On Mon, 23 Aug 2021 at 13:24, Ralf Habacker ***@***.***>
wrote:

> I'm using default pathes on a local development system with openSUSE.
>
> Further investigation shows that this issue happens when the glslang
> package wasn't found. In that case cmake tries to search for an installed
> package named 'vsg_glslang' (see
> https://github.com/vsg-dev/VulkanSceneGraph/blob/master/CMakeLists.txt#L85)
> , which is generated by the VulkanSceneGraph package and therefore could
> not be available on building vulkanSceneGraph.
>

My assumption is that Claudio was building vsgExamples and found the issue
with finding vsg_glslang.cmake rather than the build of the
VulkanSceneGraph missing the vsg_glslang.cmake.

**Comment by rhabacker** [comment]
No problems with building binaries vsg from the git master branch on my personal build projects at build.opensuse.org

- [opensuse - gcc](https://build.opensuse.org/project/show/home:rhabacker:branches:games) 
- [MinGW32 - gcc](https://build.opensuse.org/project/show/home:rhabacker:branches:games:mingw32)

but I recognized that specific settings may be required:

- opensuse  
```
<cmake-command> \
  -DCMAKE_RELWITHDEBINFO_POSTFIX= \
```
to remove the 'rd' suffix 

- MinGW32
```
<cmake-command> \
  -DCMAKE_RELWITHDEBINFO_POSTFIX= \
  -DVulkan_LIBRARY=<cmake-install-prefix>/lib/libvulkan.dll.a
```
to remove the 'rd' suffix and let /usr/share/cmake/Modules/FindVulkan.cmake find the vulkan import library.
